Upgrade to Laravel 10.x
givebloodorg/doesangue-core pull request #88
Opened 2023-09-15 19:59 UTC by sukuasoft

O projecto foi atualizado para última versão do Laravel 10.x. Este PR foi enviado após realizar os testes e validações do sistema. Como forma de avançar na issues seguintes.

2023-09-19 22:45 UTC, JoseCage requested changes
Requer fix no Namespace do CampaignSeeder

2023-09-19 22:45 UTC, JoseCage commented on app/Modules/Campaign/Database/Seeders/CampaignsSeeder.php
> +namespace GiveBlood\Modules\Campaing\Database\Seeders;
A expressão anterior estava correcta para "Campanha".

2023-09-20 06:28 UTC, sukuasoft commented on app/Modules/Campaign/Database/Seeders/CampaignsSeeder.php
> +namespace GiveBlood\Modules\Campaing\Database\Seeders;
Creio que não havia percebido, mas já esta mudado.

2023-09-20 19:14 UTC, JoseCage commented on app/Modules/Users/User.php
> +        'country_id',
`country_code` é um código ISO, logo "code" faz mais sentido

2023-09-21 06:17 UTC, sukuasoft commented on app/Modules/Users/User.php
> +        'country_id',
Fiz está mudança por conta das migrações que várias partes do código estão como country_id, isso porque relacionaste a tabela users com table countries.
Então terei que fazer alterações em todos lugares onde estava country_id

2023-09-21 06:33 UTC, JoseCage commented on app/Modules/Users/User.php
> +        'country_id',
Boa. Vou reavaliar essa relação.

2023-09-22 19:03 UTC, JoseCage requested changes

2023-09-22 19:03 UTC, JoseCage commented on app/Support/Http/Controllers/CampaignController.php
> +        }
@sukuasoft Podemos usar o `findOrFail::` e já retorna uma exceção caso o registo não seja encontrado.

2023-09-23 10:02 UTC, sukuasoft commented on app/Support/Http/Controllers/CampaignController.php
> +        }
Boa, farei isso. Vou até revisar mesmo todo o código novamente.

2023-10-11 21:59 UTC, merged